# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-27 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='pdf document name')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='PDFUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048, unique=True, verbose_name='project title')),
                ('is_live', models.BooleanField()),
                ('documents', models.ManyToManyField(related_name='urls', related_query_name='urls', to='app_crawler.PDFDocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='pdfurls',
            index=models.Index(fields=[b'url'], name='app_crawler_url_f09e57_idx'),
        ),
    ]
